export const CHANGE_SCREEN = 'CHANGE_SCREEN';

export const MAIN_MENU = 'MAIN_MENU';
export const SHOW_GENERATION_VALUES = 'SHOW_GENERATION_VALUES';
export const RUN_MODEL = 'RUN_MODEL';
export const EXPORT_DATA = 'EXPORT_DATA';

export const SAVE_GENERATION_VALUES = 'SAVE_GENERATION_VALUES';
